#!/command/with-contenv sh
exec 2>&1
export PG_META_PORT=8080
export PG_META_HOST=127.0.0.1
export PG_META_DB_HOST="${POSTGRES_HOST}"
export PG_META_DB_PORT="${POSTGRES_PORT}"
export PG_META_DB_NAME="${POSTGRES_DB}"
export PG_META_DB_USER=supabase_admin
export PG_META_DB_PASSWORD="${POSTGRES_PASSWORD}"
export CRYPTO_KEY="${JWT_SECRET}"
cd /opt/meta
exec node dist/server/server.js
