name: location_history
description: "A Privacy-Focused Location Tracker"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0

  # Dependency Injection
  get_it: ^8.0.3 

  # Routing
  go_router: ^14.8.1  

  # -- Functional Programming & Error Handling
  fpdart: ^1.1.1

  # Data Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.7

  # UI & Design
  webfabrik_theme:
    git: https://github.com/ton-An/webfabrik_theme
  elevated_flex:
    git: https://github.com/ton-An/elevated_flex
  flutter_carousel_widget:
    git: https://github.com/ton-An/flutter_carousel_widget
  gap: ^3.0.1
  dotted_line: ^3.2.3
  simple_shadow: ^0.3.1

  # Maps & Location
  flutter_map: ^8.0.0
  latlong2: ^0.9.1

  # Networking
  dio: ^5.8.0+1
  http: ^1.3.0

  # Data Storage
  flutter_secure_storage: ^9.2.4
  supabase_flutter: ^2.8.4

  # Media
  video_player: ^2.9.3

  # Utilities
  in_date_utils: ^1.2.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  mock_supabase_http_client: ^0.0.3+2

  # Linting & Analysis
  flutter_lints: ^5.0.0
  pubspec_checker: ^1.1.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  
  # App Icon File Generation
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/videos/
    - assets/images/