# yaml-language-server: $schema=https://unpkg.com/@powersync/service-schema@1.13.4/json-schema/powersync-config.json

# See https://docs.powersync.com/self-hosting/telemetry
telemetry:
  # Opt out of reporting anonymized usage metrics to PowerSync telemetry service
  disable_telemetry_sharing: true

# Settings for source database replication
replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI

      # SSL settings
      sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'

# Connection settings for sync bucket storage
storage:
  type: postgresql
  # This accepts the same parameters as a postgres data source connection
  uri: !env PS_STORAGE_SOURCE_URI
  sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'

# The port which the PowerSync API server will listen on
port: !env PS_PORT

# Specify sync rules
sync_rules:
  path: sync_rules.yaml

# Client (application end user) authentication settings
client_auth:
  supabase: true
  supabase_jwt_secret: !env PS_SUPABASE_JWT_SECRET

  # JWKS audience
  audience: ["powersync-dev", "powersync"]