# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json
#
# See Documentation for more information:
# https://docs.powersync.com/usage/sync-rules
#
# Note that changes to this file are not watched.
# The service needs to be restarted for changes to take effect.

bucket_definitions:
  public_info:
    data:
      - |
        SELECT
          id,
          name,
          value
        FROM public_info
      - |
        SELECT
          id,
          role,
          permission,
          created_at,
          updated_at,
          deleted_at
        FROM role_permissions
        WHERE role_permissions.deleted_at IS NULL

  user_data:
    parameters: SELECT request.user_id() as user_id
    data:
      - |
        SELECT
          id,
          email,
          username,
          created_at,
          updated_at,
          deleted_at
        FROM users
        WHERE users.id = bucket.user_id
      - |
        SELECT
          id,
          user_id,
          name,
          model,
          os_id,
          os_version,
          app_version,
          manufacturer,
          created_at,
          updated_at
        FROM devices
        WHERE devices.user_id = bucket.user_id
      - |
        SELECT
          id,
          user_id,
          device_id,
          latitude,
          longitude,
          coordinates_accuracy,
          speed,
          speed_accuracy,
          heading,
          heading_accuracy,
          ellipsoidal_altitude,
          altitude_accuracy,
          activity_type_id,
          activity_confidence,
          recording_trigger,
          battery_level,
          is_device_charging,
          timestamp
        FROM raw_location_data
        WHERE raw_location_data.user_id = bucket.user_id
      - |
        SELECT
          id,
          user_id,
          start_location_id,
          end_location_id
        FROM activity_segments
        WHERE activity_segments.user_id = bucket.user_id
      - |
        SELECT
          id,
          user_id,
          name,
          arrival_location_id,
          departure_location_id
        FROM visits
        WHERE visits.user_id = bucket.user_id
      - |
        SELECT
          id,
          user_id,
          role,
          invited_at,
          accepted_at,
          created_at,
          updated_at,
          deleted_at
        FROM user_roles
        WHERE user_roles.user_id = bucket.user_id

  user_management_data:
    parameters: |
      SELECT DISTINCT 'user_management' as scope
      FROM user_roles
      INNER JOIN role_permissions
        ON role_permissions.role = user_roles.role
      WHERE user_id = request.user_id()
        AND user_roles.accepted_at IS NOT NULL
        AND user_roles.deleted_at IS NULL
        AND role_permissions.permission = 'read.users'
        AND role_permissions.deleted_at IS NULL
    data:
      - |
        SELECT
          id,
          email,
          username,
          created_at,
          updated_at,
          deleted_at
        FROM users
      - |
        SELECT
          id,
          user_id,
          role,
          invited_at,
          accepted_at,
          created_at,
          updated_at,
          deleted_at
        FROM user_roles
