-- Custom types
create type public.app_role as enum ('admin', 'user');

-- USERS
create table
  public.users (
    id uuid references auth.users not null primary key,
    username text not null,
    email text not null unique
  );

alter table public.users enable row level security;

-- USER ROLES
create table
  public.user_roles (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users on delete cascade not null,
    role app_role not null,
    unique (user_id, role)
  );

alter table public.user_roles enable row level security;

-- Public Settings
create table
  public.public_settings (
    id bigint generated by default as identity primary key,
    name text not null,
    value jsonb not null
  );

alter table public.public_settings enable row level security;

alter policy "Enable read access for all users" on "public"."public_settings" to public using (true);

insert into
  public.public_settings (name, value)
values
  ('is_set_up', 'false');