name: Run tests

# ToDo: Add flutter analyze step that outputs to somewhere (where tho? :D)

on:
  push:
    branches: [main]
    paths:
      - app/**

  pull_request:
    branches: [main]
    paths:
      - app/**
      
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Restore packages
        run: flutter pub get

      - name: Generate build runner files
        run: flutter pub run build_runner build

      - name: Install junitreport
        run: flutter pub global activate --source git https://github.com/ton-An/dart-junitreport

      - name: Run tests
        run: flutter test --coverage --machine | tojunit -o junit.xml

      - name: Upload Test Coverage
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          verbose: true

      - name: Upload Test Results
        uses: codecov/test-results-action@v1
        with:
          files: junit.xml
                
