name: Run dart analysis

on:
  push:
    branches: [main]
    paths:
      - app/**

  pull_request:
    branches: [main]
    paths:
      - app/**
      
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Restore packages
        run: flutter pub get

      - name: Generate build runner files
        run: flutter pub run build_runner build
              
      - uses: invertase/github-action-dart-analyzer@v3
        with:
          fatal-infos: false
          fatal-warnings: false